### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by Fonta1n3**
Bare minimum viable product for macOS and iOS.

Add a signer, add a psbt either by pasting, uploading a `.psbt` file (as defined by BIP174), or by scanning a QR code of raw base64 text.

Once signed you will be alerted and can export the psbt as base64 text, QR code or as a `.psbt` file.

### CODE REVIEW

**Comment by Fonta1n3** [comment]
Latest commits add ability to support either outputting or taking in animated `crypto-psbt` UR QR codes. @ChristopherA this is ready for review and testing. **Testnet only**

To test you can delete account tprv's from Gordian Wallet then create a transaction. Export the psbt as text, paste it in to Gordian Signer then sign the psbt (add the words from Gordian Wallet of course), then tap export as QR to get the animated QR's.

I recommend exporting the animated QR on macOS then scan them with iOS device as QR scanning is not supported on Catalyst.

To test a static `crypto-psbt` UR QR you can use this: [https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-006/6.png](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-006/6.png)

**Review by ChristopherA — CHANGES_REQUESTED** [review]
Tested NACK: Built on macOS Catalina (10.15.6) (inside VMware 11.5.6) using Xcode 11.7.

I'm getting, while using fresh build VM, after building for target iPhone SE Simulator:

```
git clone git@github.com:BlockchainCommons/GordianSigner-Catalyst.git
cd GordianSigner-Catalyst
gh pr checkout 2
open GordianSigner/GordianSigner.xcodeproj/
```

```
There is no XCFramework found at '/Users/admin/projects/github/BlockchainCommons/BCLibWallySwift/build/CLibWally.xcframework'.
There is no XCFramework found at '/Users/admin/projects/github/BlockchainCommons/BCLibWallySwift/build/LibWally.xcframework'.
```

In the Swift Package Dependencies, I'm only seeing one item `URKit 2.0.0" — I'm not seeing a  libwally anywhere.

**Review by ChristopherA — COMMENTED** [review]
Note that this repo is inconsistent with our other xcode repos, having the `.xcodeprojt` not be inside a folder `Xcode/`, but instead inside a folder named `GordianSigner`.

**Review by ChristopherA — COMMENTED** [review]
On the offchance that not having carthage was preventing this build, I did a `brew install carthage`, and cleaned the build folder, but I get the exact same build error.

**Comment by Fonta1n3** [comment]
> Tested NACK: Built on macOS Catalina (10.15.6) (inside VMware 11.5.6) using Xcode 11.7.
> 
> 
> 
> I'm getting, while using fresh build VM, after building for target iPhone SE Simulator:
> 
> 
> 
> ```
> 
> git clone git@github.com:BlockchainCommons/GordianSigner-Catalyst.git
> 
> cd GordianSigner-Catalyst
> 
> gh pr checkout 2
> 
> open GordianSigner/GordianSigner.xcodeproj/
> 
> ```
> 
> 
> 
> ```
> 
> There is no XCFramework found at '/Users/admin/projects/github/BlockchainCommons/BCLibWallySwift/build/CLibWally.xcframework'.
> 
> There is no XCFramework found at '/Users/admin/projects/github/BlockchainCommons/BCLibWallySwift/build/LibWally.xcframework'.
> 
> ```
> 
> 
> 
> In the Swift Package Dependencies, I'm only seeing one item `URKit 2.0.0" — I'm not seeing a  libwally anywhere.
> 
> 
> 
> 

Ah, yes need to commit the frameworks. For some reason git is not seeing them even though its not specified in gitignore... Will fix.

**Comment by Fonta1n3** [comment]
> Note that this repo is inconsistent with our other xcode repos, having the `.xcodeprojt` not be inside a folder `Xcode/`, but instead inside a folder named `GordianSigner`.

Well with this method people can just click "open in xcode" via the github web UI which makes it really slick. Otherwise that option is not possible.

**Comment by ChristopherA** [comment]
Then should the other repos be changed so that they can also “open in Xcode”? I’m just seeking consistency.

**Comment by Fonta1n3** [comment]
> Then should the other repos be changed so that they can also “open in Xcode”? I’m just seeking consistency.

I think so, being able to make a single click from the web gui is really nice.

**Comment by Fonta1n3** [comment]
> Tested NACK: Built on macOS Catalina (10.15.6) (inside VMware 11.5.6) using Xcode 11.7.
> 
> I'm getting, while using fresh build VM, after building for target iPhone SE Simulator:
> 
> ```
> git clone git@github.com:BlockchainCommons/GordianSigner-Catalyst.git
> cd GordianSigner-Catalyst
> gh pr checkout 2
> open GordianSigner/GordianSigner.xcodeproj/
> ```
> 
> ```
> There is no XCFramework found at '/Users/admin/projects/github/BlockchainCommons/BCLibWallySwift/build/CLibWally.xcframework'.
> There is no XCFramework found at '/Users/admin/projects/github/BlockchainCommons/BCLibWallySwift/build/LibWally.xcframework'.
> ```
> 
> In the Swift Package Dependencies, I'm only seeing one item `URKit 2.0.0" — I'm not seeing a libwally anywhere.

https://github.com/BlockchainCommons/GordianSigner-Catalyst/pull/2/commits/5ae9f8c383b214c6330ea05aaeca0ced33068cdd fixes this, you should be able to click "open in xcode" as the only build instructions. The frameworks were not actually copied into the project which is what the issue was.

**Review by ChristopherA — CHANGES_REQUESTED** [review]
I have pulled latest version of this PR, but I still get a build error. Slightly different than before:

/Users/admin/projects/github/BlockchainCommons/GordianSigner-Catalyst/GordianSigner/CLibWally.xcframework/ios-x86_64-simulator/libwallycore.a: No such file or directory

```
Showing Recent Issues
ProcessXCFrameworkLibrary /Users/admin/projects/github/BlockchainCommons/GordianSigner-Catalyst/GordianSigner/CLibWally.xcframework/ios-x86_64-simulator/libwallycore.a /Users/admin/Library/Developer/Xcode/DerivedData/GordianSigner-flstedfjpdiebffkqpyfwujlrvxk/Build/Products/Debug-iphonesimulator/libwallycore.a (in target 'GordianSigner' from project 'GordianSigner')
    cd /Users/admin/projects/github/BlockchainCommons/GordianSigner-Catalyst/GordianSigner
    builtin-copy /Users/admin/projects/github/BlockchainCommons/GordianSigner-Catalyst/GordianSigner/CLibWally.xcframework/ios-x86_64-simulator/libwallycore.a /Users/admin/Library/Developer/Xcode/DerivedData/GordianSigner-flstedfjpdiebffkqpyfwujlrvxk/Build/Products/Debug-iphonesimulator

error: /Users/admin/projects/github/BlockchainCommons/GordianSigner-Catalyst/GordianSigner/CLibWally.xcframework/ios-x86_64-simulator/libwallycore.a: No such file or directory (in target 'GordianSigner' from project 'GordianSigner')
```

**Comment by Fonta1n3** [comment]
@ChristopherA could you delete the local repo, delete the app, delete derived data, clean the project and try again. I can not reproduce this. Other option will be to compile the frameworks on your machine: https://github.com/BlockchainCommons/BCLibwallySwift

**Comment by ChristopherA** [comment]
No, confirmed tonight with fresh VM, new xcode never ever run before, new clone, pr #2. Get same build error as yesterday.

```
/Users/admin/projects/github/BlockchainCommons/GordianSigner-Catalyst/GordianSigner/CLibWally.xcframework/ios-x86_64-simulator/libwallycore.a: No such file or directory
```

**Comment by Fonta1n3** [comment]
> No, confirmed tonight with fresh VM, new xcode never ever run before, new clone, pr #2. Get same build error as yesterday.
> 
> 
> 
> ```
> 
> /Users/admin/projects/github/BlockchainCommons/GordianSigner-Catalyst/GordianSigner/CLibWally.xcframework/ios-x86_64-simulator/libwallycore.a: No such file or directory
> 
> ```
> 
> 

Ugh, ok. Looks like it could be the gitignore... Even though we use the same frameworks in all projects and have never had this issue, will try again.

**Comment by Fonta1n3** [comment]
@ChristopherA https://github.com/BlockchainCommons/GordianSigner-Catalyst/pull/2/commits/cd9f394e6ce203c7248d7f9ac645f45dd14cedf5 should fix the issue.

**Comment by ChristopherA** [comment]
Still no luck on build. Fresh install of Catalina, fresh install xcode:

```
 cd ~/projects/github/BlockchainCommons
 git clone git@github.com:BlockchainCommons/GordianSigner-Catalyst.git
gh pr checkout 2
open GordianSigner/GordianSigner.xcodeproj/
```

and build results in:

```
GordianSigner Group
Swift Compiler Error Group
/Users/admin/Library/Developer/Xcode/DerivedData/GordianSigner-flstedfjpdiebffkqpyfwujlrvxk/Build/Products/Debug-iphonesimulator/LibWally.framework/Modules/LibWally.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:4:8: No such module 'CLibWally'
/Users/admin/projects/github/BlockchainCommons/GordianSigner-Catalyst/GordianSigner/GordianSigner/Signer.swift:10:8: Failed to load module 'LibWally'
```

**Comment by Fonta1n3** [comment]
@ChristopherA hope the 16th try is a charm... I replaced the entire `.gitignore` with what I know works for us on other projects and indeed there were some `CLibWally` simulator module maps etc that were not yet committed. Appreciate your patience!

**Comment by ChristopherA** [comment]
Built ACK: Built on macOS Catalina (10.15.6) (inside VMware 11.5.6) using Xcode 11.7.

Did not test PSBT signing functionality, but merging to master as this is the first real build.

**Pull request merged**
