### PR TITLE
Major update.

### PR DESCRIPTION
**Pull request by Fonta1n3**
This PR revamps the app and expands functionality significantly.

There are now four tabs:

1. psbts
 - the app will now encrypt and save each psbt you add, allowing you to store them for later use/signing. Each psbt is assigned a lifehash based on its binary data, is labelled as complete or incomplete, and includes a date added label. Users may export these psbts or tap "detail" to sign them and see the psbts in detail. When signing a psbt the app will prompt the user to add the signer needed to sign the psbt allowing the user to only temporarily store the private keys if desired (if the app is unable to sign as is).

- when viewing "psbt detail" the user will see each input along with each participant (public keys) which are displayed as either the keyset label that is associated with that public key or an "unknown" and whether that public key has been signed for or not.

2. signers
- each signer is displayed as per its editable label, fingerprint and lifehash based on its "BIP39 entropy". Users may add signers and opt out of storing private keys. When a signer is added its public keyset is automatically stored, its lifehash, date added and fingerprint are also saved. A key icon will appear if the app has stored the encrypted private keys.

3. keysets
- keysets are automatically created/added/stored when a user adds a signer or an account map. The editable label is displayed, the fingerprint, the keyset itself, an icon denoting whether the keyset is associated with one of our signers or not, an icon which denotes whether the keyset has been shared via an account map or not, a lifehash of the signer the keyset may be associated with (if any), a key icon showing whether the app is storing private keys for that keyset or not, an export button for exporting the keyset and finally a "add to map" button for optionally adding the keyset to a "policy map".

4. account maps/policy maps
- a policy map is an incomplete account map, once a policy map has a complete set of keysets it becomes an account map. Users may import account maps via qr code scan or create policy maps by tapping the + button. When creating a policy map the user has to choose the m of n, for now the app hard codes segwit "BIP48" derivation for policy maps and keysets. The editable label is displayed, the m of n, the script type, the participants (keyset labels), a green circle for account maps indicating it is complete, a yellow half circle indicating it is incomplete (policy map) and finally an export button for exporting as a qr code.

This is not yet thoroughly tested and there will be bugs. Known issue is that Libwally does not display any info about inputs when a psbt is complete!

### CODE REVIEW

**Comment by ChristopherA** [comment]
I'm getting `There is no XCFramework found at '/Users/admin/projects/github/BlockchainCommons/BCLibWallySwift/build/CLibWally.xcframework'.` trying to build on Catalina 10.15.7 and Xcode 11.5.

Do you believe that this version can built on the above? If not, in this PR you should update the build documentation.

**Comment by Fonta1n3** [comment]
> I'm getting `There is no XCFramework found at '/Users/admin/projects/github/BlockchainCommons/BCLibWallySwift/build/CLibWally.xcframework'.` trying to build on Catalina 10.15.7 and Xcode 11.5.
> 
> Do you believe that this version can built on the above? If not, in this PR you should update the build documentation.

That version should be fine. I have been updating the frameworks frequently and its possible they did not get committed due to `.gitignore` again. Will have a look. You can always build `BCLibwallySwift` and add the xcframeworks manually too.

**Comment by Fonta1n3** [comment]
@ChristopherA The latest commits enable mainnet and added some missing functionality around parsing output addresses to see if they match any Account Maps as well as displaying the derivation paths for each input/output and utilizing the term `co-signer` in the UI instead of `keyset` which I think will be significantly easier for users to understand.

**Comment by ChristopherA** [comment]
I was not able to build this version for both Mac & iPod touch 7th Gen targets (on Big Sur 11.1 Xcode 14.0.2):

```
Swift Compiler Error Group
/Users/christophera/projects/github/BlockchainCommons/GordianCosigner-Catalyst/GordianSigner/View Controllers/KeysetsViewController.swift:10:8: Could not find module 'LibWally' for target 'arm64-apple-ios-macabi'; found: x86_64-apple-ios-macabi, x86_64
Uncategorized Group
Command CompileSwift failed with a nonzero exit code
```

/cc @wolfmcnally

**Comment by ChristopherA** [comment]
@wolfmcnally — this is the one that needs a look at libwally compilation.

**Review by ChristopherA — COMMENTED** [review]
I am able to successfully build for iPhone simulator on my M1 Mac, and also build for M1 and Rosetta, but with the M1 and Rosetta build I immediately get this error or launch (see #15).

**Review by ChristopherA — APPROVED** [review]
Build ACK. Build PR #4 on my MacBook Air (M1, 2020), using macOS BigSur 11.1 with Xcode Version 12.3 (12C33), and targets simulator ( iPod Touch (7th),  iPhone 12 Max Pro, iPad 8th) and "My Mac" (m1), My Mac (Rosetta), and My Mac (Designed for iPad). 

Did some basic testing of creating co-signers, but did not do full regression testing. But this PR is sufficient for release to alpha (testnet) main branch.

**Comment by ChristopherA** [comment]
Two minor warning notes that should be addressed:

When I first pull PR,  I get a warning to "update settings". 

The second is a warning that I got when I build for "My Mac (Designed for iPad)"

```
2021-01-16 15:48:36.907468-0800 Gordian Cosigner[53051:2104328] Unable to load the Interface Builder file LifehashSeedView.nib because the object archive is missing. Valid nib files must contain either keyedobjects.nib, objects.nib, or data.nib. Full path: /private/var/folders/cr/sqs4t9hs52d7q7jlylb41nr80000gp/X/E8B44F26-6A54-5369-AF76-ADB6B56603AF/d/Wrapper/Gordian Cosigner.app/LifehashSeedView.nib
```

Neither are worthy of holding up this PR.

/cc @wolfmcnally

**Pull request merged**
